apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi-container
        image: customerapi-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  selector:
    app: customerapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
